# Generated by Django 5.2 on 2025-05-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Carousel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
                (
                    "poster_url",
                    models.CharField(max_length=255, verbose_name="轮播图图片路径"),
                ),
                (
                    "description",
                    models.CharField(
                        max_length=128, null=True, verbose_name="轮播图描述"
                    ),
                ),
                (
                    "target_url",
                    models.CharField(
                        max_length=255, null=True, verbose_name="跳转链接"
                    ),
                ),
            ],
            options={
                "verbose_name": "轮播图模型",
            },
        ),
        migrations.CreateModel(
            name="Vajra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
                (
                    "icon_url",
                    models.CharField(max_length=255, verbose_name="金刚区图标路径"),
                ),
                (
                    "text",
                    models.CharField(
                        max_length=64, null=True, verbose_name="金刚区文字"
                    ),
                ),
                (
                    "target_url",
                    models.CharField(
                        max_length=255, null=True, verbose_name="跳转地址"
                    ),
                ),
            ],
            options={
                "verbose_name": "金刚区模型",
            },
        ),
    ]
