# Generated by Django 5.2 on 2025-05-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_carousel_vajra"),
    ]

    operations = [
        migrations.CreateModel(
            name="Token",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
                ("token", models.CharField(max_length=255, verbose_name="token")),
                ("user_id", models.IntegerField(verbose_name="用户ID")),
                (
                    "expires",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="过期时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "用户token模型",
            },
        ),
    ]
